/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetofinal;

import org.junit.jupiter.api.Test;

import projetofinal.LP2.Aluno;
import projetofinal.LP2.Gerente;
import projetofinal.LP2.Instrutor;
import projetofinal.LP2.Recepcionista;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test 
    void TesteExtremo() { //testes para casos extremos (nulls e 0)

        Instrutor classUnderTest = new Instrutor(0, 0, null, null, null, null, null, null, null, null);
        assertNotNull(classUnderTest.getClass());

        Recepcionista classUnderTest2 = new Recepcionista(0, 0, null, null, null, null, null, null, null, null);
        assertNotNull(classUnderTest2.getClass());

        Gerente classUnderTest3 = new Gerente(0, 0, null, null, null, null, null, null, null, null, 0);
        assertNotNull(classUnderTest3.getClass());

        Aluno classUnderTest4= new Aluno(null, null, null, null, null, null, null, null, null, classUnderTest);
        assertNotNull(classUnderTest4.getClass());
        
    }

}
